name: CI-CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  opta-deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # You only need to include this step if you have opta files outside of this repo
      - name: Setup ssh
        uses: webfactory/ssh-agent@v0.4.1
        with:
          # if you don't have a github SSH key, you can generate one here: 
          # https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
          ssh-private-key: ${{ secrets.GITHUB_SSH_KEY }}

      - name: Configure AWS credentials	
        uses: aws-actions/configure-aws-credentials@v1	
        with:	
          # This aws account should have admin permissions
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}	
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}	
          aws-region: us-east-1	

      - name: Build image
        run: docker build -t app:latest -f Dockerfile .

      - name: Update deployment
        # Note that this version should be the same as your CLI version
        uses: run-x/deploy-action@v0.6 
        with:
          env: runx-staging
          image: app:latest
          tag: ${{ github.sha }}