name: CI-CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  opta-deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup ssh
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Configure AWS credentials	
        uses: aws-actions/configure-aws-credentials@v1	
        with:	
          aws-access-key-id: ${{ secrets.DEPLOYER_AWS_ACCESS_KEY }}	
          aws-secret-access-key: ${{ secrets.DEPLOYER_AWS_SECRET_ACCESS_KEY }}	
          aws-region: us-east-1	

      - name: Build image
        run: docker build -t app:latest -f Dockerfile .

      - name: Update deployment
        uses: run-x/deploy-action@v0.6
        with:
          env: runx-staging
          image: app:latest
          tag: ${{ github.sha }}
